### ISSUE TITLE
Release extension alpha (0.1.0)

### ISSUE THREAD

**Issue by ComputerBread** [yt-react-db/issue-tracker#14]
### Prerequisite:

- [x] #2

### Todo

- [x] modify BACKEND_URL value
- [x] zip it (learn how to do that)
- [x] make a release in github
  - [x] link issues (what's done & known issues)
- [x] publish it on chrome
- [x] publish it on firefox
- front
  - [x] update front end to link it & talk about it
  - [x] add a note to tell that, “changes (to permissions) can take up to 24 hours to be noticed by extension users”
- then test it #21

**Comment by ComputerBread** [comment]
Ok, the extension is published on the [chrome web store](https://chrome.google.com/webstore/detail/yt-react-db/cbdghbddaeanhpeodhbbelalccdhlcem) and [AMO](https://addons.mozilla.org/en-US/firefox/addon/yt-react-db/).

But #20 it doesn't work with google chrome which is very problematic, because there's no easy fix (maybe I should spend more time verifying this), and I need to modify the whole process, and store extra information (custom channel URL).

Started making a few test: #21 

And created an extension page on [yt-react-db.com](https://yt-react-db.com/extension)
